[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [switch]$Check,

    [Parameter(Mandatory = $false)]
    [string]$RootPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-RepositoryRoot {
    param(
        [Parameter(Mandatory = $false)]
        [string]$CandidateRoot
    )

    if (-not [string]::IsNullOrWhiteSpace($CandidateRoot)) {
        return (Resolve-Path -Path $CandidateRoot -ErrorAction Stop).Path
    }

    return (Resolve-Path (Join-Path -Path $PSScriptRoot -ChildPath "../../..")).Path
}

function ConvertTo-SkillTitle {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FileName
    )

    $tokens = @($FileName -split '[-_]+' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    if ($tokens.Count -eq 0) {
        return $FileName
    }

    $textInfo = [System.Globalization.CultureInfo]::InvariantCulture.TextInfo
    $parts = @()
    foreach ($token in $tokens) {
        $parts += $textInfo.ToTitleCase($token.ToLowerInvariant())
    }

    return ($parts -join ' ')
}

function ConvertTo-MarkdownTableValue {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    return (($Value -replace '\|', '\\|').Trim())
}

function Get-SkillMetadata {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SkillPath,

        [Parameter(Mandatory = $true)]
        [string]$Root
    )

    $content = Get-Content -Path $SkillPath -Raw -ErrorAction Stop
    $triggerPattern = '<!--\s*trigger:\s*(?<keywords>[^|]+?)\s*\|\s*(?<description>[^|]+?)\s*\|\s*(?<category>[^|>]+?)\s*\|\s*(?<details>[^>]+?)\s*-->'
    $match = [System.Text.RegularExpressions.Regex]::Match(
        $content,
        $triggerPattern,
        [System.Text.RegularExpressions.RegexOptions]::IgnoreCase
    )

    if (-not $match.Success) {
        $relative = [System.IO.Path]::GetRelativePath($Root, $SkillPath)
        throw "E_LLM_TRIGGER_METADATA_MISSING: Missing trigger metadata comment in '$relative'."
    }

    $category = $match.Groups['category'].Value.Trim()

    $relativePath = [System.IO.Path]::GetRelativePath($Root, $SkillPath).Replace('\\', '/')
    $skillLinkPath = $relativePath
    if ($skillLinkPath.StartsWith('.llm/', [System.StringComparison]::OrdinalIgnoreCase)) {
        $skillLinkPath = $skillLinkPath.Substring(5)
    }

    $detailsPath = $match.Groups['details'].Value.Trim()
    if ([string]::IsNullOrWhiteSpace($detailsPath)) {
        $detailsPath = $skillLinkPath
    }
    if ($detailsPath.StartsWith('.llm/', [System.StringComparison]::OrdinalIgnoreCase)) {
        $detailsPath = $detailsPath.Substring(5)
    }

    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($SkillPath)

    return [pscustomobject]@{
        Name          = ConvertTo-SkillTitle -FileName $baseName
        RelativePath  = $relativePath
        SkillCardLink = "./$skillLinkPath"
        DetailsLink   = "./$detailsPath"
        Keywords      = ConvertTo-MarkdownTableValue -Value $match.Groups['keywords'].Value
        Description   = ConvertTo-MarkdownTableValue -Value $match.Groups['description'].Value
        Category      = ConvertTo-MarkdownTableValue -Value $category
    }
}

function New-GeneratedIndexLines {
    param(
        [Parameter(Mandatory = $true)]
        [System.Collections.Generic.List[object]]$Skills
    )

    $categoryOrder = @('Core', 'Quality', 'Platform', 'GitHub')
    $lines = New-Object System.Collections.Generic.List[string]

    $lines.Add('# Skills Index') | Out-Null
    $lines.Add('') | Out-Null
    $lines.Add('This file is generated. Do not edit generated sections manually.') | Out-Null
    $lines.Add('') | Out-Null
    $lines.Add('<!-- BEGIN GENERATED SKILLS INDEX -->') | Out-Null
    $lines.Add('<!-- Generated by Scripts/Utils/Quality/Update-LlmSkillsIndex.ps1. Do not edit by hand. -->') | Out-Null

    $categories = @($Skills | ForEach-Object { $_.Category } | Sort-Object -Unique)
    $orderedCategories = New-Object System.Collections.Generic.List[string]

    foreach ($name in $categoryOrder) {
        if ($categories -contains $name) {
            $orderedCategories.Add($name) | Out-Null
        }
    }

    foreach ($name in $categories) {
        if ($orderedCategories -notcontains $name) {
            $orderedCategories.Add($name) | Out-Null
        }
    }

    $isFirstCategory = $true
    foreach ($category in $orderedCategories) {
        $categorySkills = @($Skills | Where-Object { $_.Category -eq $category } | Sort-Object Name, RelativePath)
        if ($categorySkills.Count -eq 0) {
            continue
        }

        if ($isFirstCategory) {
            $lines.Add('') | Out-Null
            $isFirstCategory = $false
        }
        $lines.Add("## $category") | Out-Null
        $lines.Add('') | Out-Null
        $lines.Add('| Skill Card | Expanded Guide | Trigger Keywords | Usage |') | Out-Null
        $lines.Add('| --- | --- | --- | --- |') | Out-Null

        foreach ($skill in $categorySkills) {
            $lines.Add("| [$($skill.Name)]($($skill.SkillCardLink)) | [Expanded Guide]($($skill.DetailsLink)) | $($skill.Keywords) | $($skill.Description) |") | Out-Null
        }

        $lines.Add('') | Out-Null
    }

    if ($lines[$lines.Count - 1] -ne '') {
        $lines.Add('') | Out-Null
    }
    $lines.Add('<!-- END GENERATED SKILLS INDEX -->') | Out-Null

    return @($lines)
}

$repoRoot = Get-RepositoryRoot -CandidateRoot $RootPath
$indexPath = Join-Path -Path $repoRoot -ChildPath '.llm/skills-index.md'
$skillsRoot = Join-Path -Path $repoRoot -ChildPath '.llm/skills'

if (-not (Test-Path -Path $indexPath -PathType Leaf)) {
    throw "E_LLM_SKILLS_INDEX_MISSING: Required file not found at '$indexPath'."
}

if (-not (Test-Path -Path $skillsRoot -PathType Container)) {
    throw "E_LLM_SKILLS_DIR_MISSING: Required directory not found at '$skillsRoot'."
}

$skillFiles = @(
    Get-ChildItem -Path $skillsRoot -Filter '*.md' -File -Recurse -ErrorAction Stop |
    Sort-Object FullName
)

$skillEntries = New-Object System.Collections.Generic.List[object]
foreach ($skillFile in $skillFiles) {
    $skillEntries.Add((Get-SkillMetadata -SkillPath $skillFile.FullName -Root $repoRoot)) | Out-Null
}

$generatedLines = New-GeneratedIndexLines -Skills $skillEntries
$newIndexContent = (($generatedLines -join "`n") + "`n")
$currentIndexContent = Get-Content -Path $indexPath -Raw -ErrorAction Stop

if ($Check) {
    if ($newIndexContent -ne $currentIndexContent) {
        throw "E_LLM_INDEX_STALE: Generated skills index is stale. Run Update-LlmSkillsIndex.ps1 and commit .llm/skills-index.md."
    }

    Write-Host 'LLM skills index is up to date.'
    return
}

if ($newIndexContent -eq $currentIndexContent) {
    Write-Host 'LLM skills index is already up to date.'
    return
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($indexPath, $newIndexContent, $utf8NoBom)
Write-Host "Updated generated skills index in $indexPath"
